---
title: "Initial data exploration"
date: "Oct 12, 2019"
author: "Margaret Reed, Daniel Hwang, Yi Chen"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-libraries}
library(tidyverse)
library(broom)
library(dplyr)
library(lubridate)
library(stringr)
library(tidytext)
library(textdata)
library(SnowballC)


data(stop_words)
afinn <- get_sentiments("afinn")
bing <- get_sentiments("bing")
nrc <- get_sentiments("nrc")
```

```{r import-data}
data <- read_csv("data.csv") %>%
  tidy()
```


```{r lubridate}
data <- data %>%
  mutate(dateTime = ymd_hms(CreatedDate),
         Year = year(dateTime),
         Month = month(dateTime),
         Day = day(dateTime),
         Date = paste(Year, Month, Day, sep = "-") %>% ymd() %>% as.Date()) %>%
  select(-dateTime, -Day, -Month, -Year) %>%
  select(Date, everything())
```


```{r date-viz}
data %>%
  ggplot(aes(x = Date)) +
  geom_histogram(bins = 100)
```

```{r small-data}
smallData <- data %>%
  slice(1:20)
```


```{r small-data-test}
textSmallData <- smallData %>%
  select(Date, Title, StoryID) %>%
  unnest_tokens(word, Title)

textFreq <- data %>%
  select(Date, Title, StoryID) %>%
  unnest_tokens(word, Title) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

textFreq %>%
  filter(n>= 100) %>%
  ggplot(aes(x = word, y = n)) +
    geom_col()
```


```{r bing-edit}
bing <- bing %>%
  mutate(sentValue = case_when(
    sentiment == "negative" ~ -1,
    sentiment == "positive" ~ 1
  ))
```



```{r sentiment-begin}
textData <- data %>%
  select(Date, Title, StoryID) %>%
  unnest_tokens(word, Title) %>%
  inner_join(nrc) # %>%
  # group_by(StoryID) %>%
  # summarize(meanSent = mean(value),
  #           tot_words = n())
```


```{r hits}
# hitsSentData <- full_join(data, textData) %>%
#   select(StoryID, Hits, meanSent) %>%
#   drop_na()
# 
# hitsSentData %>%
#   ggplot(aes(x = meanSent, y = Hits)) +
#   geom_point()
```



```{r countrySplit}
dataUSA <- subset(data, Country_USA == 1)
dataGBR <- subset(data, Country_GBR == 1)
dataCAN <- subset(data, Country_CAN == 1)

dataUSA %>%
  select(Title, Hits)

```

```{r gether-data}
gatheredData <- data %>%
  pivot_longer(Tag_None:Tag_CoStarGreenReport, names_to = "Tags") 
```

```{r tags_data}
# condenses tags into one tags column and their boolean into hasTag
allTags <- gather(data, "tags", "hasTag", 13:35) 
allTags <- allTags[order(allTags$StoryID),]

# to find all tags associated with an article, filter for hasTag is true
allTags %>%
  filter(StoryID == 184098 & hasTag == 1) %>%
  select(Title, tags)

# creates a dataframe with story titles and their tag counts
tagCounts <- allTags %>%
  group_by(StoryID) %>%
  count(hasTag == 1) %>%
  select(StoryID, n) %>%
  rename(numTags = n)

# previous operation returns both true and false, removing all FALSE
toDelete <- seq(1, nrow(tagCounts), 2)
tagCounts <- tagCounts[-toDelete, ]

data <- data %>%
  full_join(tagCounts)
```



```{r tags_plots, fig.width=5}
# correlating number of tags with hit count
data %>%
  select(Hits, numTags) %>%
  ggplot(aes(numTags)) + 
  geom_bar(fill = "Blue") + 
  scale_x_continuous(name = "Number of tags", breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "Hit count") + 
  theme_minimal() + 
  labs(title = "Number of Tags Correlated with Hit Count")





# --------------------------------Now plotting by tag popularity

tagPop <- allTags %>%
  count(tags, hasTag) 

tagPop <- tagPop %>%
  filter(hasTag == 1) %>%
  arrange(n) %>%
  select(tags, n) %>%
  rename(total = n)

tagPop <- mutate_if(tagPop, 
                is.character, 
                str_replace_all, pattern = "Tag_", replacement = "")


tagPop %>%
  arrange(desc(total)) %>%
  slice(0:10) %>%
  ggplot(aes(x = reorder(tags, -total), y = total)) +
  geom_col(fill = "Blue") + 
  scale_x_discrete(name = "Top 10 tags") +
  scale_y_continuous(name = "# of stories with tag") + 
  theme_minimal() + 
  labs(title = "Top 10 Most Popular Tags")

```


```{r model}
data1 <- data %>%
  drop_na()

first_model <- lm(Hits ~ data1$numTags + Date + AuthorID + Country_USA + Country_CAN + Country_GBR + data1$Tag_None + data1$Tag_National + data1$Tag_Office + data1$Tag_Industrial + data1$Tag_Retail + data1$Tag_People + data1$Tag_Investment + data1$Tag_Analytics + data1$Tag_Development + data1$Tag_Finance + data1$Tag_Multifamily + data1$Tag_Hospitality + data1$Tag_Company + data1$Tag_Healthcare + data1$Tag_CompaniesPeople + data1$Tag_Lease + data1$Tag_Sale + data1$Tag_MixedUse + data1$Tag_SpecialPurpose, data = data1)

tidy(first_model)
glance(first_model)
```


```{r tagpop-pull}
tagPop %>%
  select(tags) %>%
  pull()
```

