---
title: "CoStar Interactive"

output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: scroll
runtime: shiny
---

```{r load-packages, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(broom)
library(dplyr)
library(lubridate)
library(stringr)
library(tidytext)
library(textdata)
library(SnowballC)
library(DT)
```

```{r load-data, include = FALSE}
data <- read_csv("data.csv") %>%
  as.tibble()

data <- data %>%
  mutate(dateTime = ymd_hms(CreatedDate),
         Year = year(dateTime),
         Month = month(dateTime),
         Day = day(dateTime),
         Date = paste(Year, Month, Day, sep = "-") %>% ymd() %>% as.Date()) %>%
  select(-dateTime, -Day, -Month, -Year) %>%
  select(Date, everything()) %>%
  mutate(Title = as.character(Title), 
         Summary = as.character(Summary),
         Body = as.character(Body))
```

```{r more-cleaning, include = FALSE}
allTags <- gather(data, "tags", "hasTag", 13:35) 
allTags <- allTags[order(allTags$StoryID),]

# creates a dataframe with story titles and their tag counts
tagCounts <- allTags %>%
  group_by(StoryID) %>%
  count(hasTag == 1) %>%
  select(StoryID, n) %>%
  rename(numTags = n)

# previous operation returns both true and false, removing all FALSE
toDelete <- seq(1, nrow(tagCounts), 2)
tagCounts <- tagCounts[-toDelete, ]

# Appends numTags to last column of dataframe
data <- data %>%
  full_join(tagCounts)
```


Sidebar {.sidebar}
=======================================================================

### Dataset Characteristics

```{r chooseTags}
hr()
selectInput("tagSelected", "Choose a tag to search for:",
                  list("All", 
                       `RealEstate` = list("Tag_Development", "Tag_Land", "Tag_Lease", "Tag_MixedUse", "Tag_Retail", "Tag_Sale", "SpecialPurpose"),
                       `Workforce` = list("Tag_Company", "Tag_CompaniesPeople", "Tag_Office"),
                       `Business` = list("Tag_Analytics", "Tag_Finance", "Tag_Investment"),
                       `PublicServices` = list("Tag_Healthcare", "Tag_Hospitality", "Tag_Multifamily", "Tag_People", "Tag_PublicSector"),
                       `Sectors/Misc` = list("Tag_Events", "Tag_Industrial", "Tag_Legal", "Tag_National")
                  ),
                  selected = "",
                  multiple = FALSE)
```



```{r chooseCountry}
hr()

radioButtons(inputId = "country",
                         label = "Select countries:",
                         choices = c("All", "Canada", "US", "GB") ,
                         selected = "All")
```


```{r chooseDateRange}
hr()

sliderInput("TheDates",
                    "Move the sliders to select a date range:",
                    min = as.Date("2016-03-31","%Y-%m-%d"),
                    max = as.Date("2018-09-28","%Y-%m-%d"),
                    value=c(as.Date("2017-04-05"), as.Date("2018-04-13")),
                    timeFormat=("%Y-%m-%d"))
```

```{r countrySplit}
# splits countries into separate datasets
US <- subset(data, Country_USA == 1)
GB <- subset(data, Country_GBR == 1)
Canada <- subset(data, Country_CAN == 1)

```

```{r makeReactive}



allTags <- allTags %>%
  filter(hasTag == 1)

# handles user country choice
countryData <- reactive({
  if (input$country == "All"){ 
    data
  } else if (input$country == "Canada"){ 
    Canada
  } else if (input$country == "US"){ 
    US
  } else if (input$country == "GB"){
    GB
  }
})


# handles user date range and tag choice
sel_data <- reactive({
  if (input$tagSelected == "All") { 
    countryData() %>%
    drop_na() %>%
    select(-Body) %>%
    filter(
      between(Date, input$TheDates[1], input$TheDates[2])
      )
    } else {
  allTags %>%
        filter(tags == input$tagSelected) %>%
        full_join(countryData()) %>%
        drop_na() %>%
        select(-Body) %>%
        filter(
          between(Date, input$TheDates[1], input$TheDates[2])
          )
      } 
  })



```


Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Stories found {.value-box}
```{r totalStory}
renderValueBox({
  valueBox(value = count(sel_data()))
})

```

### Average hits per story {.value-box}

```{r avg-hitsPerStory}
renderValueBox({
  valueBox(value = round(mean(sel_data()$Hits, na.rm = TRUE), 2))
})
```

### Average number of tags per story {.value-box}

```{r avg-tagsPerStory}
renderValueBox({
  valueBox(value = round(mean(sel_data()$numTags, na.rm = TRUE), 2))
})
```

### Percentage of all data contained in your search

```{r percentGauge}


renderGauge({
  perc <- nrow(sel_data())/nrow(data)*100
  
  gauge(round(perc, 2), min = 0, max = 100, symbol = "%")
})


```

Row
-----------------------------------------------------------------------

### Visualization {data-width=700}

```{r plotDataReactive}

# setting up reactive plot data
plotData <- reactive({ 
  sel_data() %>%
  select(Date, Title, StoryID) %>%
  unnest_tokens(word, Title) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)
})

#plotData()$word <- factor(textFreq$word, levels = textFreq$word[order(desc((textFreq$n)))])
```

```{r plot_rendering}
renderPlot({
  plotData() %>%
    slice(0:10) %>%
    ggplot(aes(x = reorder(word, -n), y = n)) +
    geom_col(fill = "dodgerblue") +
    labs(x = "Words", y = "Frequency", title = "Most Frequently Occurring Words in Titles of Stories")
  })
```

Data
=======================================================================

### About the data {data-width=100}

This [flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/) uses data 
from CoStar.

The data used in the analysis is shown below.

```{r data-table}
renderDataTable({
  datatable(sel_data() %>%
               select(-(11:34))
             ) 
})
```