---
title: "Part 03 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
runtime: shiny
---

```{r load-packages, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(janitor)
```


```{r load-data, include = FALSE}
nfl_draft <- read_csv("nfl_draft.csv") %>%
  janitor::clean_names() %>%
  select(-x33) %>%
  filter(is.na(player_id) == FALSE)
```

```{r save-fields, include = FALSE}
min_year  <- 1985
max_year  <- 2015
n_tot_years <- (max_year - min_year) + 1
draft_round <- nfl_draft %>% distinct(rnd) %>% arrange(rnd) %>% filter(!is.na(rnd)) %>% pull(rnd)
```
Sidebar {.sidebar}
=======================================================================

### NFL Draft Statistics

```{r-filter-data}
hr()
sliderInput(inputId = "year", label = "Year drafted",
            min = min_year, max = max_year,
            value = c(2001, max_year), step = 1, sep = "")
hr()
checkboxGroupInput(inputId = "draft_round", label = "Draft Round",
                   choices = draft_round, 
                   selected = c(1, 2, 3)
                   )
hr()
x_var <- reactive({ syms(input$x) })
y_var <- reactive({ syms(input$y) })
sel_data <- reactive({
  nfl_draft %>%
    dplyr::filter(
      between(year, input$year[1], input$year[2]),
      rnd %in% input$draft_round
      ) %>%
    dplyr::filter(!is.na( !!!x_var() ), !is.na( !!!y_var() ))
})
```


Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Percentage of players with data on selected variables {.value-box}

```{r}
renderGauge({
  
  n_sel_player <- nfl_draft %>%
    dplyr::filter(Rnd %in% input$draft_round) %>%
    distinct(player_id) %>%
    nrow()
  p <- round( nrow(sel_data()) / n_sel_player * 100, 0)
  
  gauge(p, min = 0, max = 100, symbol = "%", 
        gaugeSectors(success = c(80, 100), warning = c(40, 79), 
                     danger = c(0, 39)))
})
```

### Average career approximate value {.value-box}

```{r-avg-carAV}
renderValueBox({
  valueBox(value = round(mean(sel_data()$car_av, na.rm = TRUE), 2), 
           icon = "glyphicon-hand-up")
})
```

### Average age of players {.value-box}

```{r}
renderValueBox({
  valueBox(value = round(mean(sel_data()$age, na.rm = TRUE), 2), 
           icon = "glyphicon-hourglass")
})
```

Row
-----------------------------------------------------------------------

### Variable choices {data-width=340}

```{r-choose-variables}
selectInput(
  inputId = "x", label = "X-axis",
  choices = c(
    "Career Approximate Value" = "car_av", 
    "Approximate Value for First 4 Years" = "first4av",
    "Age at Time of Draft" = "age",
    "Number of Years as Starter" = "st",
    "Number of All-Pro Selections" = "ap1",
    "Number of Pro Bowl Selections" = "pb",
    "Games Played" = "g"
    ),
  selected = "car_av"
  )
selectInput(
  inputId = "y", label = "Y-axis",
  choices = c(
    "Career Approximate Value" = "car_av",
    "Approximate Value for First 4 Years" = "first4av",
    "Age at Time of Draft" = "age",
    "Number of Years as Starter" = "st",
    "Number of All-Pro Selections" = "ap1",
    "Number of Pro Bowl Selections" = "pb",
    "Games Played" = "g"
    ),
  selected = "g"
  )
xlab <- reactive({
  case_when(
    input$x == "car_av" ~  
      "Career Approximate Value",
    input$x == "first4av"        ~  
      "Approximate Value for First 4 Years",
    input$x == "age"              ~ 
      "Age at Time of Draft",
    input$x == "st"       ~ 
      "Number of Years as Starter",
    input$x == "ap1"       ~ 
      "Number of All-Pro Selections",
    input$x == "pb"           ~ 
      "Number of Pro Bowl Selections",
    input$x == "g"          ~ 
      "Games Played"
  )
})
ylab <- reactive({
  case_when(
    input$y == "car_av" ~  
      "Career Approximate Value",
    input$y == "first4av"        ~  
      "Approximate Value for First 4 Years",
    input$y == "age"              ~ 
      "Age at Time of Draft",
    input$y == "st"       ~ 
      "Number of Years as Starter",
    input$y == "ap1"       ~ 
      "Number of All-Pro Selections",
    input$y == "pb"           ~ 
      "Number of Pro Bowl Selections",
    input$y == "g"          ~ 
      "Games Played"
  )
})
br()
```

### Visualization {data-width=700}

```{r}
renderPlot({
  ggplot(data = sel_data(),
         mapping = aes_string(x = input$x, y = input$y, color = "rnd")) +
  geom_point(size = 2, alpha = 0.8) +
  theme_minimal() +
  labs(x = xlab(), y = ylab(), color = "Draft Round")
  })
```

Data
=======================================================================

### About the data

This [flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/) uses data 
from [Pro Football Reference](http://www.pro-football-reference.com/).

The data used in the analysis is shown below.

```{r-data-table}
DT::renderDataTable({
  datatable( sel_data() )
})
```